server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50

spring:
  application:
    name: catalog-services

management:
  endpoints:
    web:
      exposure:
        include: refresh