version: "3.8"
services:
  catalog-services:
    image: "catalog-services"
    container_name: "catalog-services"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001